name: Android CD

on:
  push:
    branches: [ "main" ]

env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  SIGNED_KEY_ALIAS: ${{ secrets.SIGNED_KEY_ALIAS }}
  SIGNED_KEY_PASSWORD: ${{ secrets.SIGNED_KEY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
  tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run tests
      run: ./gradlew test

  build_apk:
    needs: tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Checkout keystore rep
      uses: actions/checkout@v2
      with:
        repository: ${{ secrets.KEYSTORE_GIT_REP }}
        token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
        path: app/keystore

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build apk and aab
      run:  |
        ./gradlew assembleRelease --stacktrace
        ./gradlew bundleRelease
    - name: Upload apk
      uses: actions/upload-artifact@v4
      with:
        name: Insurance_calculator.apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk
    - name: Upload aab
      uses: actions/upload-artifact@v4
      with:
        name: Insurance_calculator.aab
        path: app/build/outputs/bundle/release/app-release-unsigned.aab
